# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - libopenmpi-dev
    - openmpi-bin
    - graphviz

# Build documentation in the doc/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Python requirements to build the docs
python:
  install:
    - method: pip
      path: .

