name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    name: ${{ matrix.os }} CPython ${{ matrix.python }} ${{ matrix.mpi }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu-18.04", "ubuntu-20.04" ]
        python: [ "3.7", "3.8", "3.9", "3.10" ]
        mpi: [ "openmpi", "mpich" ]
        exclude:
          - os: ubuntu-18.04
            python: 3.8
          - os: ubuntu-18.04
            python: 3.9
          - os: ubuntu-18.04
            python: 3.10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install CPython ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
          architecture: x64
      - name: Install MPI ${{ matrix.mpi }}
        run: |
          if [[ "${{ matrix.mpi }}" == "openmpi" ]]; then
              sudo apt install libopenmpi-dev openmpi-bin
          elif [[ "${{ matrix.mpi }}" == "mpich" ]]; then
              sudo apt install mpich
          else
              exit 1
          fi
          mpirun --version
      - name: Setup virtual environment
        run: |
          python -m venv venv
      - name: Install mpi4torch
        run: |
          . venv/bin/activate
          pip install . nose2 mpi4py
      - name: Run Tests (np=2)
        run: |
          . venv/bin/activate
          #mpirun -np 2 python -c 'from mpi4torch import COMM_WORLD; print("Communicator size:", COMM_WORLD.size) if COMM_WORLD.rank == 0 else exit(0)'
          mpirun -np 2 nose2
      - name: Run Tests (np=5)
        run: |
          . venv/bin/activate
          if [[ "${{ matrix.mpi }}" == "openmpi" ]]; then
              mpirun -np 5 --oversubscribe nose2
          else
              mpirun -np 5 nose2
          fi
      - name: Run Tests (np=7)
        run: |
          . venv/bin/activate
          if [[ "${{ matrix.mpi }}" == "openmpi" ]]; then
              mpirun -np 7 --oversubscribe nose2
          else
              mpirun -np 7 nose2
          fi

